CREATE TABLE clientes (
    id SERIAL PRIMARY KEY,
    fecha INT NOT NULL
    tasa TEXT NOT NULL,
);

CREATE TABLE clientes (
    id SERIAL PRIMARY KEY,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tasa TEXT NOT NULL
);
